---
title: "Mini Meta Analysis (Effects across 4 studies)"
author: "Ivan Grahek"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    theme: default
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## About the code

Experiment: Control adjustment costs - 4 experiments
Code written by: Ivan Grahek (2023)
Description: Code for generating the forest plot with the control costs across 4 studies 

\newpage

# Load the libraries 


```{r, message=FALSE}
# clear the environment
rm(list=ls()) 

# set seed
set.seed(42) 

#load packages and install them if they're not installed. the pacman package will 
#automatically check for the requested packages and download & install them if they are not on the computer.
if (!require("pacman")) install.packages("pacman")
pacman::p_load(brms,here,broom,knitr,tidyverse,plyr,cowplot,emmeans,tidybayes,viridis,MASS)


```


# Enter the range normalized distances

```{r,warning=T, message=T}

# Study 1
# Create a data frame
Study1Distance = data.frame(
  Parameter = c("Distance"),
  Effect = c("Control Adjustment Cost"),
  Mean = c(0.11),
  CI_lower = c(-0.01),
  CI_upper = c(0.23)
)

# Study 2
# Create a data frame
Study2Distance = data.frame(
  Parameter = c("Distance","Distance","Distance"),
  Effect = c("Cost (Low distance)","Cost (Medium distance)","Cost (High distance)"),
  Mean = c(0.07,0.17,0.24),
  CI_lower = c(-0.05,0.03,0.11),
  CI_upper = c(0.20,0.31,0.38)
)

# Study 3
# Create a data frame
Study3Distance = data.frame(
  Parameter = c("Distance","Distance"),
  Effect = c("Cost (Long time)","Cost (Short time)"),
  Mean = c(0.11,0.24),
  CI_lower = c(-0.07,0.06),
  CI_upper = c(0.30,0.41)
)

# Study 4
# Create a data frame
Study4Distance = data.frame(
  Parameter = c("Distance","Distance","Distance"),
  Effect = c("Cost (Low switch frequency)",
                               "Cost (Medium switch frequency)",
                               "Cost (High switch frequency)"),
  Mean = c(0.07,0.25,0.26),
  CI_lower = c(-0.11,0.07,0.06),
  CI_upper = c(0.24,0.44,0.45)
)


Studies_Distance = rbind(Study1Distance,Study2Distance,Study3Distance,Study4Distance)
Studies_Distance$Effect = factor(Studies_Distance$Effect, levels = rev(unique(Studies_Distance$Effect)))


# 
# # Create the forest plot
# ggplot(Studies_Distance, aes(x = Mean, y = Effect)) +
#   geom_point(size = 3) +
#   geom_errorbarh(aes(xmin = CI_lower, xmax = CI_upper), height = 0.1) +
#   geom_vline(xintercept = 0, linetype = "dashed", color = "gray40") +
#   facet_wrap(~Parameter)+
#   labs(title = "Forest Plot", x = "Mean", y = NULL) +
#   theme_minimal() +
#   theme(legend.position = "bottom")


# Save the figure
pdf(file="../../Manuscript/figures/Figure_6.pdf",height=10,width=12)

p = ggplot(Studies_Distance, aes(x = Mean, y = Effect)) +
  geom_point(size = 3) +
  geom_errorbarh(aes(xmin = CI_lower, xmax = CI_upper),height=0) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  ylab("Cost") + 
  xlab("Regression estimate") + 
  xlim(c(-0.2,0.5))+
  facet_wrap(~Parameter, scales = "free_x")+
    theme(axis.line = element_line(colour = "black"),
        plot.margin=grid::unit(c(5,5,5,5), "mm"),
        axis.title.y = element_text(margin = margin(t = 0, r = 0, b = 0, l = 0),color="black"),
        text = element_text(size=33,color = "black"),
        panel.border = element_rect (colour = "black", fill = F),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.x = element_text(color="black"),
        axis.text.y = element_text(color="black"),
        axis.ticks = element_line(color = "black"),
        legend.position = c(0.8, 0.25),
        legend.background = element_rect(fill = "transparent", color = NA))  
p
dev.off()



```


